defaults:
  - _self_
  - domain: wheel.yaml
  - override hydra/launcher: submitit_slurm # joblib

horizon: 500000
algo: nnegreedy
update_every: 1.2
noise_std: ${domain.noise_param}
delta: 0.01
ucb_regularizer: 1
bonus_scale: 0.1
batch_size: 128
max_updates: 30
lr: 1e-3
buffer_capacity: ${horizon}
weight_decay: 0
reset_model_at_train: False
layers: 150
weight_l2features: 0.
weight_spectral: 0
weight_orth: 0
weight_mse: 1
random_init_weights: True
weight_rayleigh: 0
epsilon_min: 0.001
epsilon_start: 1
epsilon_decay: cbrt
time_random_exp: 1000
train_reweight: False
glrt_scale: 1
mingap_clip: 0.001
weight_certainty: 0
weight_uncertainty: 0
weight_trace: 0
weight_min_features: 0
weight_min_random: 0
check_glrt: True
normalize_features: True
use_maxnorm: True
use_relu: True
adaptive_bonus_linucb: True
save_model_at_train: False

# misc
seed: 1
device: cpu
use_tb: true
use_wandb: false
exp_name: "default_name"

hydra:
  run:
    dir: ./output/${now:%Y.%m.%d}/${now:%H%M%S}_${algo}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${algo}
    subdir: ${hydra.job.num}
  # launcher:
  #   timeout_min: 4000
  launcher:
    timeout_min: 4000
    cpus_per_task: 4
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${algo}/.slurm
    partition: devlab
  job_logging :
      formatters:
        simple:
          format: '%(message)s'
      root:
        handlers: [file]
