defaults:
  - _self_
  - domain: statlog.yaml
  - override hydra/launcher: submitit_local # joblib


lr: 1e-3
batch_size: 128
layers: [150,100]
weight_decay: 0
seed: 0
max_epochs: 20
device: cpu
use_relu: true

hydra:
  # run:
  #   dir: ./output/${now:%Y.%m.%d}/${now:%H%M%S}
  # sweep:
  #   dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  #   subdir: ${hydra.job.num}
  # launcher:
  #   timeout_min: 4000
  # launcher:
  #   timeout_min: 4000
  #   cpus_per_task: 4
  #   gpus_per_node: 1
  #   tasks_per_node: 1
  #   mem_gb: 160
  #   nodes: 1
  #   submitit_folder: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${algo}/.slurm
  #   partition: learnlab
  job_logging :
      formatters:
        simple:
          format: '%(message)s'
      root:
        handlers: [file]
